/*
CREATE TABLE ACCOUNT
(
	ACNO VARCHAR2(10) PRIMARY KEY,
	AHNAME VARCHAR2(20),
	BALANCE NUMBER(12,2)
);

INSERT INTO ACCOUNT VALUES('PNB2001','Soumyadeep Adak',25600.02);
INSERT INTO ACCOUNT VALUES('SBI2023','Hritick Das',236540.53);
INSERT INTO ACCOUNT VALUES('UCO2004','Sourav Joshi',5000.60);
INSERT INTO ACCOUNT VALUES('UBI2010','Raju Singh',50310.04);
INSERT INTO ACCOUNT VALUES('UBI5000','Rakesh Das',380.30);
COMMIT;
*/

SET SERVEROUTPUT ON

DECLARE
	ACCNO ACCOUNT.ACNO%TYPE;
	AHNAME ACCOUNT.AHNAME%TYPE;
	BALANCE ACCOUNT.BALANCE%TYPE;
	MIN_BALANCE CONSTANT NUMBER(5,2):=500.00;

BEGIN
	SELECT ACNO, AHNAME, BALANCE INTO ACCNO, AHNAME, BALANCE FROM ACCOUNT WHERE ACNO='&ACCOUNT_NO';
	
	IF(BALANCE<MIN_BALANCE) THEN
		UPDATE ACCOUNT SET BALANCE = BALANCE - 100 WHERE ACNO = ACCNO;
		COMMIT;
		BALANCE := BALANCE - 100;
        	DBMS_OUTPUT.PUT_LINE('Rs. 100 deducted due to low balance.');
		DBMS_OUTPUT.PUT_LINE('UPDATED ACCOUNT INFO:');
	ELSE
        	DBMS_OUTPUT.PUT_LINE('Balance is sufficient. No deduction.');
	END IF;

	DBMS_OUTPUT.PUT_LINE('ACNO     AHNAME           BALANCE');
	DBMS_OUTPUT.PUT_LINE(ACCNO||'  '||AHNAME||'  '||BALANCE);

EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('INVALID ACCOUNT NO.');
END;
/

/*
OUTPUT:
------
SQL> @C:\Users\DELL\OneDrive\Desktop\PLSQL\Ass9Q2a.sql
Enter value for account_no: PNB2001
old   8:        SELECT ACNO, AHNAME, BALANCE INTO ACCNO, AHNAME, BALANCE FROM ACCOUNT WHERE ACNO='&ACCOUNT_NO';
new   8:        SELECT ACNO, AHNAME, BALANCE INTO ACCNO, AHNAME, BALANCE FROM ACCOUNT WHERE ACNO='PNB2001';
Balance is sufficient. No deduction.
ACNO     AHNAME           BALANCE
PNB2001  Soumyadeep Adak  25600.02

PL/SQL procedure successfully completed.
*/